title: HIS School
description: "HIS International School (HIS) is a Christian K-12 grade international
school."
author: Yong Lim
avatar: /logo.png
email: yong.lim@gmail.com

url: "https://hisschool.yonglim.com"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

subscribe: false

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
# twitter:
#   username: ngzhio
#   card: summary
# logo: logo.png
# social:
#   name: Shangzhi Huang
#   links:
#     - https://twitter.com/ngzhio
#     - https://www.facebook.com/ngzhio
#     - https://github.com/ngzhio
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en

