title: HIS School
description: "HIS International School (HIS) is a Christian K-12 grade international
school."
avatar: /logo.png
author: Yong Lim
email: yong.lim@gmail.com

url: "https://hisschool.yonglim.com"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

subscribe: false

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

lang: en

skin: sunrise
